# Generated by Django 2.2.7 on 2022-12-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_drinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='dish_name',
            new_name='drink_name',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='small_price',
        ),
    ]
