# Generated by Django 2.2.7 on 2022-12-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20221218_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='sub_filling',
            new_name='subs',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='small_price',
        ),
    ]
