# Generated by Django 2.2.7 on 2022-12-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20221218_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salad',
            new_name='Snack',
        ),
        migrations.AlterModelOptions(
            name='snack',
            options={'verbose_name': 'List of Snack', 'verbose_name_plural': 'List of Snack'},
        ),
    ]
