# Generated by Django 2.2.7 on 2022-12-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20221218_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='price',
            new_name='large_price',
        ),
        migrations.AddField(
            model_name='snack',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
