# Generated by Django 2.2.7 on 2022-12-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20221218_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snack',
            new_name='Snacks',
        ),
    ]
