# Generated by Django 2.2.7 on 2022-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20221218_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='price',
            new_name='bottle_price',
        ),
        migrations.AddField(
            model_name='drinks',
            name='can_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
